#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

set -e

cd ~/app-root/runtime/

# create dir to put all our stuff
mkdir -p couchdb
cd couchdb

if [ ! -e js-1.8.5 ]; then
    # get spidermonkey
    wget http://ftp.mozilla.org/pub/mozilla.org/js/js185-1.0.0.tar.gz
    tar -xzf js185-1.0.0.tar.gz
    rm -f js185-1.0.0.tar.gz
fi

if [ ! -e otp_src_17.1 ]; then
    # get erlang
    wget http://www.erlang.org/download/otp_src_17.1.tar.gz
    tar -xzf otp_src_17.1.tar.gz
    rm -f otp_src_17.1.tar.gz
fi

if [ ! -e apache-couchdb-1.6.0 ]; then
    # get couchdb
    wget http://ftp.carnet.hr/misc/apache/couchdb/source/1.6.0/apache-couchdb-1.6.0.tar.gz
    tar -xzf apache-couchdb-1.6.0.tar.gz
    rm -f apache-couchdb-1.6.0.tar.gz
fi

if [ ! -e icu ]; then
    # get ICU
    wget http://download.icu-project.org/files/icu4c/4.8.1.1/icu4c-4_8_1_1-src.tgz
    tar -xzf icu4c-4_8_1_1-src.tgz
    rm -f icu4c-4_8_1_1-src.tgz
fi
