#!/bin/bash
# The logic to stop your application should be put in this script.
cd ~/app-root/runtime/couchdb
# export this path to make couchdb load ICU lib
export LD_LIBRARY_PATH=usr/lib/
# finally start couchdb!
etc/rc.d/couchdb stop
exit 0
